admin_client_index:
    path:     /
    defaults: { _controller: "EcommerceBundle:ClientAdmin:index" }
    methods:  GET

admin_client_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:ClientAdmin:show" }
    methods:  GET

admin_client_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:ClientAdmin:new" }
    methods:  [GET, POST]

admin_client_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:ClientAdmin:edit" }
    methods:  [GET, POST]

admin_client_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:ClientAdmin:delete" }
    methods:  DELETE
