<?php

namespace EcommerceBundle\Listener;

use Doctrine\Common\EventSubscriber;
use Doctrine\ORM\Event\LifecycleEventArgs;
use EcommerceBundle\Entity\Product;

class Product_imageListener implements EventSubscriber
{

    private $directoryImage;
    private $tempFilename;
    private $asup;

    public function __construct($directory)
    {

        $this->directoryImage = $directory;

    }

    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    public function prePersist(LifecycleEventArgs $args)
    {

        $entity = $args->getEntity();
        if (!$entity instanceof Product) {
            return;

        }

        $file = $entity->getImage();
        $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

        $file->move($this->directoryImage, $fileName);

        $entity->setImage($fileName);

    }

    public function preRemove(LifecycleEventArgs $args)
    {

        $entity = $args->getEntity();
        if (!$entity instanceof Product) {
            return;

        }

        $this->tempFilename = $entity->getImage();
    }

    public function postRemove(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();
        if (!$entity instanceof Product) {
            return;

        }

        // En PostRemove, on n'a pas acc?s ? l'id, on utilise notre nom sauvegard?
        if (file_exists($this->directoryImage . '/' . $this->tempFilename)) {
            // On supprime le fichier
            $f = $this->tempFilename;
            $this->asup = $this->directoryImage . '/' . $this->tempFilename;

            unlink($this->asup);

        }
    }

    /**
     * Returns an array of events this subscriber wants to listen to.
     *
     * @return array
     */
    public function getSubscribedEvents()
    {
        return array(
            'prePersist',
            'preRemove',
            'postRemove'
        );
    }
}

