<?php

namespace EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

    public function getProductComment($id)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.id =:id')
            ->setParameter('id', $id)
            ->leftJoin('p.comments', 'c')
            ->addSelect('c');
        return $qb
            ->getQuery()
            ->getSingleResult();

    }


}
