# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: wiwi, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main_login:
            pattern:   ^/login$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            #provider: users
            pattern:   ^/admin
            anonymous: false

            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     login

        rest:
            pattern: ^/
            anonymous: true
    #access_control:
        #- { path: ^/admin, roles: ROLE_ADMIN }

